In [80]:
import numpy as np
n, m = map(int, input().split())
arr = np.array([])
for _ in range(n):
    
    row = np.array(input().split(' ')).astype(int)
    arr = np.append(arr,row)
arr = np.reshape(arr,(n,m))
print(np.transpose(arr).astype(int))
print(arr.flatten().astype(int))

2 2 
1 3
4 5
[[1 4]
 [3 5]]
[1 3 4 5]


In [76]:
print(arr.flatten())

[1. 3. 4. 5.]


In [73]:
print(arr)

[[1. 3.]
 [4. 5.]]


In [59]:
np.size(arr)

4

In [60]:
np.reshape(arr,(n,m))

array([[1., 3.],
       [4., 5.]])

In [30]:
np.size(arr2)

4

In [31]:
print(arr2)

[1 2 3 4]


In [53]:
np.reshape(arr2,(2,2))

array([[1, 2],
       [3, 4]])